image: docker:stable

stages:
  - test

test:
  image: debian:10-slim
  stage: test
  script:
    - apt update && apt install python3 python3-pip build-essential zlib1g zlib1g-dev libjpeg-dev libpng-dev libblas-dev liblapack-dev libatlas-base-dev gfortran --yes
    - python3 -m pip install -r requirements.txt
    - python3 -m pip install -r requirements-dev.txt
    - python3 -m pytest tests/unit/tests.py
    - cd ./tests/integration_tests
    - ./run_all.sh
  tags:
    - appsec-runner
  only:
    refs:
      - merge_requests

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

secret_detection:
  tags:
    - appsec-runner
  before_script:
    - ''
