image: docker:stable

stages:
  - test

test:
  stage: test
  script:
    - apk add --no-cache python3 py3-pip
    - python3 -m pip install -r requirements.txt
    - python3 -m pytest tests.py
  tags:
    - appsec-runner
  only:
    refs:
      - merge_requests

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

secret_detection:
  tags:
    - appsec-runner
  before_script:
    - ''
